# Generated by Django 3.0.5 on 2020-04-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='full_name_student',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='health_group',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
